name: Tagged lint & build
on:
  push:
    tags:
      - "v*"
jobs:
  qa:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  flatpak-build:
    name: Flatpak Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Run Flatpak Builder
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.simoonas.marca.json
          cache: true
